/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appchatvoinguoila;


import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.Socket;
import java.util.StringTokenizer;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author ADMIN
 */
public class fm_DangNhap extends javax.swing.JFrame {

    private static String host = "localhost";
    private static int port = 1234;
    private static Socket socket;

    private static DataOutputStream out;
    private static DataInputStream in;
    
    /**
     * Creates new form fm_Client
     */
    public fm_DangNhap() {
        initComponents();
        setLocationRelativeTo(null); //set position center khi mở app
        
        ConnectFunction();
    }
    
    public void ConnectFunction(){
        try {
            socket = new Socket(host, port);
            
            System.out.println("Client connected");
      
          
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Vui lòng mở Server trước!" ,"Thông báo", JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
            //Logger.getLogger(fm_DangNhap.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public void DangNhap(){
        try {
            out = new DataOutputStream(socket.getOutputStream());
            in = new DataInputStream(socket.getInputStream());
            ExecutorService executor = Executors.newFixedThreadPool(5);
            
            SendMessage send = new SendMessage(socket, out);
            ReceiveMessage recv = new ReceiveMessage(socket, in);
            executor.execute(send);
            executor.execute(recv);
            
            
        } catch (IOException ex) {
            System.out.println("Lỗi nhập xuất");
            Logger.getLogger(fm_DangNhap.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }
    
    class SendMessage implements Runnable {
        private final DataOutputStream out;
        private final Socket socket;
  
        public SendMessage(Socket s, DataOutputStream o) {
            this.socket = s;
            this.out = o;
        }
   
        public void run() {
            try {
                String userNameAdd = textfield_Username.getText();
                String dataSend = "createAccount;" + userNameAdd;
       
                System.out.println("Input from client: " + dataSend);
                out.writeUTF(dataSend);
                out.flush();

            } catch (IOException e) {}
        }
    }

    class ReceiveMessage implements Runnable {
        private final DataInputStream in;
        private final Socket socket;
        public ReceiveMessage(Socket s, DataInputStream i) {
            this.socket = s;
            this.in = i;
        }

        public void run() {
            try {
                    String data = in.readUTF();
                    System.out.println("Receive: " + data);
                    
                    StringTokenizer strToken = new StringTokenizer(data, ";");
                    String messageReceive = strToken.nextToken();
                    String userName = strToken.nextToken();
                    
                    if (messageReceive.equals("Đã thêm username!")){
                        fm_WaitingFrame fmWaiting = new fm_WaitingFrame(userName, this.socket);
                        
                        setVisible(false);
                        fmWaiting.setVisible(true);
                    }
                    
                    if (messageReceive.equals("Username đã tồn tại")){
                        JOptionPane.showMessageDialog(null, "Username này đã tồn tại! Vui lòng chọn username khác!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                        textfield_Username.setFocusable(true);
                    }
  
            } catch (IOException e) {}
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textfield_Username = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btn_DangNhap = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng nhập");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(235, 235, 235));

        jPanel2.setBackground(new java.awt.Color(60, 158, 244));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("APP CHAT VỚI NGƯỜI LẠ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
        );

        textfield_Username.setBackground(new java.awt.Color(255, 255, 255));
        textfield_Username.setForeground(new java.awt.Color(0, 0, 0));
        textfield_Username.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textfield_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_UsernameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Username:");

        btn_DangNhap.setBackground(new java.awt.Color(51, 204, 0));
        btn_DangNhap.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_DangNhap.setForeground(new java.awt.Color(0, 0, 0));
        btn_DangNhap.setText("ĐĂNG NHẬP");
        btn_DangNhap.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_DangNhap.setBorderPainted(false);
        btn_DangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DangNhapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textfield_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_DangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textfield_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(btn_DangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 88, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textfield_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_UsernameActionPerformed

    private void btn_DangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DangNhapActionPerformed
        DangNhap();
    }//GEN-LAST:event_btn_DangNhapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fm_DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fm_DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fm_DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fm_DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fm_DangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_DangNhap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField textfield_Username;
    // End of variables declaration//GEN-END:variables
}
